### ISSUE TITLE
Led it Be not working

### ISSUE THREAD

**Issue by FPPMvB** [martijnpoppen/leditbe#1]
Hi, sorry but the app is not working
Nothing happens when adding it to a flow No “stroboscope” or flashing.
For this moment I will stick to the common screensavers.
I’m uding a Homey Pro, don’t know if thats the issue?

**Comment by fellownet** [comment]
I've developed it on a Homey Pro, so yes it should work. Obvious question; have you selected "Led It Be" as your screensaver in the LED Ring section of the settings?

**Comment by fellownet** [comment]
> I've developed it on a Homey Pro, so yes it should work. Obvious question; have you selected "Led It Be" as your screensaver in the LED Ring section of the settings?

I'm going to close the issue unless you confirm that the app doesn't work, even after you've selected "Led It Be" as your screensaver.

**Comment by FPPMvB** [comment]
Hi,
No the app doesn’t work. Sorry
And yes I have selected “Led it be”
as screensaver.
The best thing In can get is a sort of strobo. But changing this to another setting is not posdible.
I have more and better options with the Led Ring Collectie app from Alex vd Berg Sorry

Met vriendelijke Groeten,
Frank van Berkel

**Comment by fellownet** [comment]
> Hi, No the app doesn’t work [..]

Can you give me the version of the Homey Firmware you are running?

**Comment by FPPMvB** [comment]
Hi,
2.5.2

Groeten Frank van Berkel

**Comment by fellownet** [comment]
I can't seem to reproduce this problem, I'm sorry. I've got a similar setup; Homey Pro, v2.5.2, and it's working flawlessly here. To make it even more weird, I'm not getting the Led Ring Collection app to work on my Homey, that's why I started this project in the first place. I'm glad that app suits your need. If you don't mind, I'm closing this issue unless there are more people with the same problem.
